### ISSUE TITLE
Editar página com informações básicas do IonicBrazil

### ISSUE THREAD

**Issue by felquis** [IonicBrazil/ionicbrazil.com#1]
É o primeiro passo ae galera, só colocar informações úteis, link para o Twitter, dizer como entrar no Slack, adicionar links dos meetups.. 

Também não sei muito bem o que seria legal, mas imagina algo bem clean, blanco, com as imagens das logos dos meetups por regiões, link para projetos que estão rolando... este tipo de coisa

**Comment by breakzplatform** [comment]
o @felquis sugeriu esse tema: http://bootstraptaste.com/theme/squadfree/

![image](https://cloud.githubusercontent.com/assets/597126/8298667/0f295a08-1942-11e5-825a-6b36851431e8.png)

Podemos usar ele de base (sem utilizar o código, apenas como referência). Se alguém tem alguma outras sugestão de tema fala aí (:

**Comment by thulioph** [comment]
Gostei do tema **+1**

**Comment by thompsonemerson** [comment]
Tá legal o template <b>+1</b>

**Comment by lucasbastianik** [comment]
Show de bola! +1

**Comment by jayrmotta** [comment]
Gostei do template!! +1

Vamos em frente ;)

**Comment by matheusrocha89** [comment]
Como tinha dito antes, tema :+1: :smile:

**Comment by washingtonsoares** [comment]
Bacana o tema! :)

**Comment by vitormalencar** [comment]
curit +1

**Comment by kidush** [comment]
bem legal o tema :+1:

**Comment by TiagoSilvaPereira** [comment]
Top o tema +1

**Comment by diegosorrilha** [comment]
tema++ :+1:

**Comment by felquis** [comment]
@IonicBrazil/moderadores Alguém poderia ajudar com ajustes na home do Ionic Brazil? http://ionicbrazil.com/

**Comment by thompsonemerson** [comment]
Posso da uma força ai, Quais seriam os ajustes @felquis ?

**Comment by felquis** [comment]
@thompsonemerson Se alguém pudesse nos ajudar com o layout seria ótimo https://github.com/IonicBrazil/ionicbrazil.com/issues/1#issuecomment-114346605 

Mas ajustes só de título e descrição + links já seria de bom tamanho pra começar.

**Comment by thompsonemerson** [comment]
Pessoas, vamos definir o conteúdo da home do site?
