### ISSUE TITLE
Ajuda com GitHub pages e Custom Domain

### ISSUE THREAD

**Issue by felquis** [IonicBrazil/ionicbrazil.com#3]
Galera, tentei configurar os DNS para apontar para a page e usar o domínio `ionicbrazil.com`, porém não tenho a menor a ideia do que estou fazendo.

Alguém poderia me dar um suporte? 

Usei este aqui, porém não tenho certeza se fiz certo https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/#configuring-an-a-record-with-your-dns-provider

Ficou dessa forma:
![image](https://cloud.githubusercontent.com/assets/736728/8331650/d5375c5e-1a5f-11e5-8bf9-6b2a2ad0f60b.png)

Alguém que já fez isso poderia me dar dicas?

**Comment by felquis** [comment]
@randsonjs @IonicBrazil/moderadores estava falando disso com vocês.

**Comment by giorgiofellipe** [comment]
Por exemplo:

![capturar](https://cloud.githubusercontent.com/assets/4589857/8332117/80cdc59c-1a62-11e5-91ed-db541b732767.PNG)

CNAME file:

```
giorgiofellipe.com.br
```

**Comment by felquis** [comment]
Quando eu salvo o A, com nome usando o domínio, ele transforma o domínio em @

**Comment by rands0n** [comment]
![screenshot from 2015-06-24 11 25 56](https://cloud.githubusercontent.com/assets/4191734/8332339/d1e3121a-1a63-11e5-8d57-930b9be214cf.png)

Um que está funcionando!

**Comment by breakzplatform** [comment]
@felquis, ele estar transformando A em @ é normal. @ significa que ele tá referenciando a se próprio.

Agora no caso, o CNAME deve aponta pra o próprio dominio, não o do Github.

**Comment by giorgiofellipe** [comment]
@joselitojunior exatamente

**Comment by rands0n** [comment]
Foi resolvido! o/

**Comment by felquis** [comment]
Galera, funcionou http://ionicbrazil.com/ 

Muito obrigado pela colaboração
